# see https://gist.github.com/dan-blanchard/7045057 for a discussion on using conda with travis ci

language: c
# use language: c to be able to use a matrix of python and numpy versions -- see https://github.com/rmcgibbo/mdtraj/blob/master/.travis.yml

sudo: false # temporary while gfortran package is required for conda problems

# specify different versions of python and numpy
env:
  - PYTHON=2.7  NUMPY_VERSION=1.9.2 CYTHON="cython>=0.20" IPYTHON="ipython=3"
  - PYTHON=2.7  NUMPY_VERSION=1.9.2 CYTHON="cython>=0.20" IPYTHON="ipython>=3"
  - PYTHON=3.4  NUMPY_VERSION=1.9.2 CYTHON="cython>=0.20" IPYTHON="ipython>=3"
  - PYTHON=3.5  NUMPY_VERSION=1.10.4 CYTHON="cython>=0.20" IPYTHON="ipython>=3"
  - PYTHON=3.6  NUMPY_VERSION=1.13.1 CYTHON="cython>=0.20" IPYTHON="ipython>=3"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda/
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - cd nose
  - wget http://star.ucl.ac.uk/~app/testdata.tar.gz
  - tar --exclude="._*" -xzvf testdata.tar.gz
  - cd ..
# ensure there are no unnecessary limits on shared memory available
  - sudo sysctl -w kernel.shmmax=268435456
  - sudo sysctl -w kernel.shmall=268435456

install:
  - conda create --yes -n ${PYTHON}_${NUMPY_VERSION} python=$PYTHON numpy=$NUMPY_VERSION scipy matplotlib nose h5py pip sphinx<1.7 pygments pandas $IPYTHON $CYTHON
  - source activate ${PYTHON}_${NUMPY_VERSION}
  - python --version
  - python setup.py install
  # Limit the number of ramses readers to 2; otherwise Travis builds have been known to run out of memory
  - echo "[ramses]" >> ~/.pynbodyrc
  - echo "parallel-read=2" >> ~/.pynbodyrc


script:
  # first test ramses without shared memory loading
  - cd nose
  - nosetests ramses_new_ptcl_format_test.py ramses_test.py
  # install posix_ipc and proceed with all tests
  - pip install posix_ipc
  - nosetests
  # check documentation build
  - if [ ${PYTHON:0:1} -eq 2 ]; then pip install sphinx_bootstrap_theme; cd ../docs; make html; fi
